version: '4'
services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: gestionfoyeramira
      MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql