version: '3.9'

services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: gestionfoyeramira
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
